AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/omniauth-krystal.rb"

Gemspec/RequireMFA:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*_spec.rb"
